### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yiluheihei** [yiluheihei/mmnet#1]
- [ ] remove mg-rast pipeline
- [ ] input: ko annotaton  profile from  jgi genome portal api, humann2, picrust
- [ ] metabolic network of single species (e.g. output of humann2)
